export const DReturnCancel = {
  6: "Solicitação de cancelamento parcial aprovada com sucesso.",
  9: "Solicitação de cancelamento total aprovada com sucesso.",
  72: "Erro: Saldo do lojista insuficiente para cancelamento de venda.",
  77: "Erro: Venda original não encontrada para cancelamento.",
  100: "Erro: Forma de pagamento e/ou Bandeira não permitem cancelamento.",
  101: "Erro: Valor de cancelamento solicitado acima do prazo permitido para cancelar.",
  102: "Erro: Cancelamento solicitado acima do valor da transação original.",
  103: "Restrição Cadastral. Cancelamento não permitido. Entre em contato com a Central de Cancelamento.",
  104: "Restrição Cadastral. Cancelamento não permitido. Entre em contato com a Central de Cancelamento.",
  105: "Restrição Cadastral. Cancelamento não permitido. Entre em contato com a Central de Cancelamento.",
  106: "Restrição Cadastral. Cancelamento não permitido. Entre em contato com a Central de Cancelamento.",
  107: "Restrição Cadastral. Cancelamento não permitido. Entre em contato com a Central de Cancelamento.",
  108: "Erro: Número do Estabelecimento (EC) não encontrado. Por favor, verifique o número enviado.",
  475: "Falha no processamento. Por favor, tente novamente.",
};
